live_config_reload = true

[window]
decorations_theme_variant = "dark"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[shell]
program = "/opt/homebrew/bin/fish"

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular"}
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic"}
size = 24


