live_config_reload = true

[colors.bright]
black = "0x6e6a86"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x796268"
text = "0x191724"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x6e6a86"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.selection]
background = "0x2A2738"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "0x796268"
text = "0x191724"

[font]
size = 20.0

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "Fixedsys Excelsior"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_title = false
opacity = 1

[window.padding]
x = 16
y = 16
