theme = "monokai_aqua"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
auto-format = false
bufferline = "multiple"
end-of-line-diagnostics= "hint"
gutters = ["diff", "line-numbers", "spacer"]
completion-trigger-len = 1
popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
