[plugins]
"rocks.nvim" = "2.43.1"
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.3"

"telescope.nvim" = "scm"
"nightfox.nvim" = "3.10.0"
"flash.nvim" = "2.1.0"
"fidget.nvim" = "1.6.0"
"rustaceanvim" = "6.0.0"
"mini.nvim" = "0.15.0"

"blink" = { git = "saghen/blink.cmp", rev = "v1.1.1" }
"monokai-pro" = { git = "loctvl842/monokai-pro.nvim" }

tree-sitter-cpp = "scm"
tree-sitter-python = "0.0.46"
tree-sitter-rust = "0.0.49"
"tokyonight.nvim" = "4.11.0"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"

[config]
auto_setup = true
colorscheme = "tokyonight"

[config.options]
number = true
relativenumber = true
incsearch = true
tabstop = 4
shiftwidth = 4
splitright = true
splitbelow = true
swapfile = false
undofile = true
expandtab = true
inccommand = "split"
signcolumn = "yes"
